### ISSUE TITLE
securityfixer-agent dependency can be removed

### ISSUE THREAD

**Issue by TobseF** [wsargent/securityfixer#4]
Just tried it out and it worked. Thanks for the example!

But before, I removed the 
``` xml
<dependency>
	<groupId>com.tersesystems</groupId>
	<artifactId>securityfixer-agent</artifactId>
	<version>2.0-SNAPSHOT</version>
	<type>pom</type>
</dependency>`
```
from the `example/pom.xml`. Or is this dependency intended?

**Comment by wsargent** [comment]
I think the agent has to be there because you're messing with the bootstrap classes https://tersesystems.com/blog/2016/01/19/redefining-java-dot-lang-dot-system/
